spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/easyhostel}
    username: ${SPRING_DATASOURCE_USERNAME:nyx}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
server:
  port: 8080
open:
  api:
    title: EasyHostel API
    version: ${api.version}
    description: API Documentation for EasyHostel Application
    serverUrl: ${server.url:http://localhost:${server.port}}
    serverName: Production Server
logging:
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: TRACE