spring:
  application:
    name: easyhostel-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/easyhostel
    username: nyx
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
open:
  api:
    title: EasyHostel API
    version: v0.1
    description: API Documentation for EasyHostel Application
    serverUrl: http://localhost:8080
    serverName: Test Server
api:
  version: v0.1
  base-path: /api/${api.version}