spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost:5432/easyhostel
    username: nyx
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
server:
  port: 8081
open:
  api:
    title: EasyHostel API
    version: ${api.version}
    description: API Documentation for EasyHostel Application
    serverUrl: http://localhost:${server.port}
    serverName: Test Server
logging:
  level:
    org:
      hibernate:
        SQL: off
        type:
          descriptor:
            sql:
              BasicBinder: TRACE